package Maple.Entity;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.*;
import java.util.UUID;
import Maple.Dto.ClientDto;

@Entity
@Table(name = "clients")
public class Client extends PanacheEntityBase {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    public UUID id;

    @Column(name = "first_name", nullable = false)
    public String firstName;

    @Column(name = "middle_name")
    public String middleName;

    @Column(name = "last_name", nullable = false)
    public String lastName;

    @Column(name = "second_last_name")
    public String secondLastName;

    @Column(nullable = false, unique = true)
    public String email;

    @Column(nullable = false)
    public String address;

    @Column(nullable = false)
    public String phone;

    @Column(nullable = false, length = 2)
    public String country;

    @Column
    public String demonym;

    public static Client toEntity(ClientDto dto) {
        if (dto == null) {
            return null;
        }

        Client client = new Client();
        // id is auto-generated by database
        client.firstName = dto.firstName;
        client.middleName = dto.middleName;
        client.lastName = dto.lastName;
        client.secondLastName = dto.secondLastName;
        client.email = dto.email.toLowerCase(); // Normalize email to lower case
        client.address = dto.address;
        client.phone = dto.phone;
        client.country = dto.country;
        // demonym will be fetched by service

        return client;
    }

}